
INSERT INTO Tipo_Persona(nombre, descripcion) VALUES ('Empleado','Persona que trabaja en la empresa');
INSERT INTO Tipo_Persona(nombre, descripcion) VALUES ('Cliente','cliente de la empresa');

INSERT INTO Paises(nombre_pais,iso,codigo_telefono) VALUES ('Afganistán','AF','93');
INSERT INTO Paises(nombre_pais,iso,codigo_telefono) VALUES ('Albania','AL','355');
INSERT INTO Paises(nombre_pais,iso,codigo_telefono) VALUES ('Alemania','DE','49');
INSERT INTO Paises(nombre_pais,iso,codigo_telefono) VALUES ('Algeria','DZ','213');
INSERT INTO Paises(nombre_pais,iso,codigo_telefono) VALUES ('Andorra','AD','376');
INSERT INTO Paises(nombre_pais,iso,codigo_telefono) VALUES ('Angola','AO','244');
INSERT INTO Paises(nombre_pais,iso,codigo_telefono) VALUES ('Anguila','AI','1 264');
INSERT INTO Paises(nombre_pais,iso,codigo_telefono) VALUES ('Antártida','AQ','672');
INSERT INTO Paises(nombre_pais,iso,codigo_telefono) VALUES ('Antigua y Barbuda','AG','1 268');
INSERT INTO Paises(nombre_pais,iso,codigo_telefono) VALUES ('Antillas Neerlandesas','AN','599');
INSERT INTO Paises(nombre_pais,iso,codigo_telefono) VALUES ('Arabia Saudita','SA','966');
INSERT INTO Paises(nombre_pais,iso,codigo_telefono) VALUES ('Argentina','AR','54');
INSERT INTO Paises(nombre_pais,iso,codigo_telefono) VALUES ('Armenia','AM','374');
INSERT INTO Paises(nombre_pais,iso,codigo_telefono) VALUES ('Aruba','AW','297');
INSERT INTO Paises(nombre_pais,iso,codigo_telefono) VALUES ('Australia','AU','61');
INSERT INTO Paises(nombre_pais,iso,codigo_telefono) VALUES ('Austria','AT','43');
INSERT INTO Paises(nombre_pais,iso,codigo_telefono) VALUES ('Azerbayán','AZ','994');
INSERT INTO Paises(nombre_pais,iso,codigo_telefono) VALUES ('Bahamas','BS','1 242');
INSERT INTO Paises(nombre_pais,iso,codigo_telefono) VALUES ('Bahrein','BH','973');
INSERT INTO Paises(nombre_pais,iso,codigo_telefono) VALUES ('Bangladesh','BD','880');
INSERT INTO Paises(nombre_pais,iso,codigo_telefono) VALUES ('Barbados','BB','1 246');
INSERT INTO Paises(nombre_pais,iso,codigo_telefono) VALUES ('Bélgica','BE','32');
INSERT INTO Paises(nombre_pais,iso,codigo_telefono) VALUES ('Belice','BZ','501');
INSERT INTO Paises(nombre_pais,iso,codigo_telefono) VALUES ('Benín','BJ','229');
INSERT INTO Paises(nombre_pais,iso,codigo_telefono) VALUES ('Bhután','BT','975');
INSERT INTO Paises(nombre_pais,iso,codigo_telefono) VALUES ('Bielorrusia','BY','375');
INSERT INTO Paises(nombre_pais,iso,codigo_telefono) VALUES ('Birmania','MM','95');
INSERT INTO Paises(nombre_pais,iso,codigo_telefono) VALUES ('Bolivia','BO','591');
INSERT INTO Paises(nombre_pais,iso,codigo_telefono) VALUES ('Bosnia y Herzegovina','BA','387');
INSERT INTO Paises(nombre_pais,iso,codigo_telefono) VALUES ('Botsuana','BW','267');
INSERT INTO Paises(nombre_pais,iso,codigo_telefono) VALUES ('Brasil','BR','55');
INSERT INTO Paises(nombre_pais,iso,codigo_telefono) VALUES ('Brunéi','BN','673');
INSERT INTO Paises(nombre_pais,iso,codigo_telefono) VALUES ('Bulgaria','BG','359');
INSERT INTO Paises(nombre_pais,iso,codigo_telefono) VALUES ('Burkina Faso','BF','226');
INSERT INTO Paises(nombre_pais,iso,codigo_telefono) VALUES ('Burundi','BI','257');
INSERT INTO Paises(nombre_pais,iso,codigo_telefono) VALUES ('Cabo Verde','CV','238');
INSERT INTO Paises(nombre_pais,iso,codigo_telefono) VALUES ('Camboya','KH','855');
INSERT INTO Paises(nombre_pais,iso,codigo_telefono) VALUES ('Camerún','CM','237');
INSERT INTO Paises(nombre_pais,iso,codigo_telefono) VALUES ('Canadá','CA','1');
INSERT INTO Paises(nombre_pais,iso,codigo_telefono) VALUES ('Chad','TD','235');
INSERT INTO Paises(nombre_pais,iso,codigo_telefono) VALUES ('Chile','CL','56');
INSERT INTO Paises(nombre_pais,iso,codigo_telefono) VALUES ('China','CN','86');
INSERT INTO Paises(nombre_pais,iso,codigo_telefono) VALUES ('Chipre','CY','357');
INSERT INTO Paises(nombre_pais,iso,codigo_telefono) VALUES ('Ciudad del Vaticano','VA','39');
INSERT INTO Paises(nombre_pais,iso,codigo_telefono) VALUES ('Colombia','CO','57');
INSERT INTO Paises(nombre_pais,iso,codigo_telefono) VALUES ('Comoras','KM','269');
INSERT INTO Paises(nombre_pais,iso,codigo_telefono) VALUES ('Congo','CG','242');
INSERT INTO Paises(nombre_pais,iso,codigo_telefono) VALUES ('Congo','CD','243');
INSERT INTO Paises(nombre_pais,iso,codigo_telefono) VALUES ('Corea del Norte','KP','850');
INSERT INTO Paises(nombre_pais,iso,codigo_telefono) VALUES ('Corea del Sur','KR','82');
INSERT INTO Paises(nombre_pais,iso,codigo_telefono) VALUES ('Costa de Marfil','CI','225');
INSERT INTO Paises(nombre_pais,iso,codigo_telefono) VALUES ('Costa Rica','CR','506');
INSERT INTO Paises(nombre_pais,iso,codigo_telefono) VALUES ('Croacia','HR','385');
INSERT INTO Paises(nombre_pais,iso,codigo_telefono) VALUES ('Cuba','CU','53');
INSERT INTO Paises(nombre_pais,iso,codigo_telefono) VALUES ('Dinamarca','DK','45');
INSERT INTO Paises(nombre_pais,iso,codigo_telefono) VALUES ('Dominica','DM','1 767');
INSERT INTO Paises(nombre_pais,iso,codigo_telefono) VALUES ('Ecuador','EC','593');
INSERT INTO Paises(nombre_pais,iso,codigo_telefono) VALUES ('Egipto','EG','20');
INSERT INTO Paises(nombre_pais,iso,codigo_telefono) VALUES ('El Salvador','SV','503');
INSERT INTO Paises(nombre_pais,iso,codigo_telefono) VALUES ('Emiratos Árabes Unidos','AE','971');
INSERT INTO Paises(nombre_pais,iso,codigo_telefono) VALUES ('Eritrea','ER','291');
INSERT INTO Paises(nombre_pais,iso,codigo_telefono) VALUES ('Escocia','GB','44');
INSERT INTO Paises(nombre_pais,iso,codigo_telefono) VALUES ('Eslovaquia','SK','421');
INSERT INTO Paises(nombre_pais,iso,codigo_telefono) VALUES ('Eslovenia','SI','386');
INSERT INTO Paises(nombre_pais,iso,codigo_telefono) VALUES ('España','ES','34');
INSERT INTO Paises(nombre_pais,iso,codigo_telefono) VALUES ('Estados Unidos de América','US','1');
INSERT INTO Paises(nombre_pais,iso,codigo_telefono) VALUES ('Estonia','EE','372');
INSERT INTO Paises(nombre_pais,iso,codigo_telefono) VALUES ('Etiopía','ET','251');
INSERT INTO Paises(nombre_pais,iso,codigo_telefono) VALUES ('Filipinas','PH','63');
INSERT INTO Paises(nombre_pais,iso,codigo_telefono) VALUES ('Finlandia','FI','358');
INSERT INTO Paises(nombre_pais,iso,codigo_telefono) VALUES ('Fiyi','FJ','679');
INSERT INTO Paises(nombre_pais,iso,codigo_telefono) VALUES ('Francia','FR','33');
INSERT INTO Paises(nombre_pais,iso,codigo_telefono) VALUES ('Gabón','GA','241');
INSERT INTO Paises(nombre_pais,iso,codigo_telefono) VALUES ('Gales','GB','44');
INSERT INTO Paises(nombre_pais,iso,codigo_telefono) VALUES ('Gambia','GM','220');
INSERT INTO Paises(nombre_pais,iso,codigo_telefono) VALUES ('Georgia','GE','995');
INSERT INTO Paises(nombre_pais,iso,codigo_telefono) VALUES ('Ghana','GH','233');
INSERT INTO Paises(nombre_pais,iso,codigo_telefono) VALUES ('Gibraltar','GI','350');
INSERT INTO Paises(nombre_pais,iso,codigo_telefono) VALUES ('Granada','GD','1 473');
INSERT INTO Paises(nombre_pais,iso,codigo_telefono) VALUES ('Grecia','GR','30');
INSERT INTO Paises(nombre_pais,iso,codigo_telefono) VALUES ('Groenlandia','GL','299');
INSERT INTO Paises(nombre_pais,iso,codigo_telefono) VALUES ('Guadalupe','GP',NULL);
INSERT INTO Paises(nombre_pais,iso,codigo_telefono) VALUES ('Guam','GU','1 671');
INSERT INTO Paises(nombre_pais,iso,codigo_telefono) VALUES ('Guatemala','GT','502');
INSERT INTO Paises(nombre_pais,iso,codigo_telefono) VALUES ('Guayana Francesa','GF',NULL);
INSERT INTO Paises(nombre_pais,iso,codigo_telefono) VALUES ('Guernsey','GG',NULL);
INSERT INTO Paises(nombre_pais,iso,codigo_telefono) VALUES ('Guinea','GN','224');
INSERT INTO Paises(nombre_pais,iso,codigo_telefono) VALUES ('Guinea Ecuatorial','GQ','240');
INSERT INTO Paises(nombre_pais,iso,codigo_telefono) VALUES ('Guinea-Bissau','GW','245');
INSERT INTO Paises(nombre_pais,iso,codigo_telefono) VALUES ('Guyana','GY','592');
INSERT INTO Paises(nombre_pais,iso,codigo_telefono) VALUES ('Haití','HT','509');
INSERT INTO Paises(nombre_pais,iso,codigo_telefono) VALUES ('Honduras','HN','504');
INSERT INTO Paises(nombre_pais,iso,codigo_telefono) VALUES ('Hong kong','HK','852');
INSERT INTO Paises(nombre_pais,iso,codigo_telefono) VALUES ('Hungría','HU','36');
INSERT INTO Paises(nombre_pais,iso,codigo_telefono) VALUES ('India','IN','91');
INSERT INTO Paises(nombre_pais,iso,codigo_telefono) VALUES ('Indonesia','ID','62');
INSERT INTO Paises(nombre_pais,iso,codigo_telefono) VALUES ('Inglaterra','GB','44');
INSERT INTO Paises(nombre_pais,iso,codigo_telefono) VALUES ('Irak','IQ','964');
INSERT INTO Paises(nombre_pais,iso,codigo_telefono) VALUES ('Irán','IR','98');
INSERT INTO Paises(nombre_pais,iso,codigo_telefono) VALUES ('Irlanda','IE','353');
INSERT INTO Paises(nombre_pais,iso,codigo_telefono) VALUES ('Irlanda del Norte','GB','44');
INSERT INTO Paises(nombre_pais,iso,codigo_telefono) VALUES ('Isla Bouvet','BV',NULL);
INSERT INTO Paises(nombre_pais,iso,codigo_telefono) VALUES ('Isla de Man','IM','44');
INSERT INTO Paises(nombre_pais,iso,codigo_telefono) VALUES ('Isla de Navidad','CX','61');
INSERT INTO Paises(nombre_pais,iso,codigo_telefono) VALUES ('Isla Norfolk','NF',NULL);
INSERT INTO Paises(nombre_pais,iso,codigo_telefono) VALUES ('Islandia','IS','354');
INSERT INTO Paises(nombre_pais,iso,codigo_telefono) VALUES ('Islas Bermudas','BM','1 441');
INSERT INTO Paises(nombre_pais,iso,codigo_telefono) VALUES ('Islas Caimán','KY','1 345');
INSERT INTO Paises(nombre_pais,iso,codigo_telefono) VALUES ('Islas Cocos (Keeling)','CC','61');
INSERT INTO Paises(nombre_pais,iso,codigo_telefono) VALUES ('Islas Cook','CK','682');
INSERT INTO Paises(nombre_pais,iso,codigo_telefono) VALUES ('Islas de Åland','AX',NULL);
INSERT INTO Paises(nombre_pais,iso,codigo_telefono) VALUES ('Islas Feroe','FO','298');
INSERT INTO Paises(nombre_pais,iso,codigo_telefono) VALUES ('Islas Georgias del Sur y Sandwich del Sur','GS',NULL);
INSERT INTO Paises(nombre_pais,iso,codigo_telefono) VALUES ('Islas Heard y McDonald','HM',NULL);
INSERT INTO Paises(nombre_pais,iso,codigo_telefono) VALUES ('Islas Maldivas','MV','960');
INSERT INTO Paises(nombre_pais,iso,codigo_telefono) VALUES ('Islas Malvinas','FK','500');
INSERT INTO Paises(nombre_pais,iso,codigo_telefono) VALUES ('Islas Marianas del Norte','MP','1 670');
INSERT INTO Paises(nombre_pais,iso,codigo_telefono) VALUES ('Islas Marshall','MH','692');
INSERT INTO Paises(nombre_pais,iso,codigo_telefono) VALUES ('Islas Pitcairn','PN','870');
INSERT INTO Paises(nombre_pais,iso,codigo_telefono) VALUES ('Islas Salomón','SB','677');
INSERT INTO Paises(nombre_pais,iso,codigo_telefono) VALUES ('Islas Turcas y Caicos','TC','1 649');
INSERT INTO Paises(nombre_pais,iso,codigo_telefono) VALUES ('Islas Ultramarinas Menores de Estados Unidos','UM',NULL);
INSERT INTO Paises(nombre_pais,iso,codigo_telefono) VALUES ('Islas Vírgenes Británicas','VG','1 284');
INSERT INTO Paises(nombre_pais,iso,codigo_telefono) VALUES ('Islas Vírgenes de los Estados Unidos','VI','1 340');
INSERT INTO Paises(nombre_pais,iso,codigo_telefono) VALUES ('Israel','IL','972');
INSERT INTO Paises(nombre_pais,iso,codigo_telefono) VALUES ('Italia','IT','39');
INSERT INTO Paises(nombre_pais,iso,codigo_telefono) VALUES ('Jamaica','JM','1 876');
INSERT INTO Paises(nombre_pais,iso,codigo_telefono) VALUES ('Japón','JP','81');
INSERT INTO Paises(nombre_pais,iso,codigo_telefono) VALUES ('Jersey','JE',NULL);
INSERT INTO Paises(nombre_pais,iso,codigo_telefono) VALUES ('Jordania','JO','962');
INSERT INTO Paises(nombre_pais,iso,codigo_telefono) VALUES ('Kazajistán','KZ','7');
INSERT INTO Paises(nombre_pais,iso,codigo_telefono) VALUES ('Kenia','KE','254');
INSERT INTO Paises(nombre_pais,iso,codigo_telefono) VALUES ('Kirgizstán','KG','996');
INSERT INTO Paises(nombre_pais,iso,codigo_telefono) VALUES ('Kiribati','KI','686');
INSERT INTO Paises(nombre_pais,iso,codigo_telefono) VALUES ('Kuwait','KW','965');
INSERT INTO Paises(nombre_pais,iso,codigo_telefono) VALUES ('Laos','LA','856');
INSERT INTO Paises(nombre_pais,iso,codigo_telefono) VALUES ('Lesoto','LS','266');
INSERT INTO Paises(nombre_pais,iso,codigo_telefono) VALUES ('Letonia','LV','371');
INSERT INTO Paises(nombre_pais,iso,codigo_telefono) VALUES ('Líbano','LB','961');
INSERT INTO Paises(nombre_pais,iso,codigo_telefono) VALUES ('Liberia','LR','231');
INSERT INTO Paises(nombre_pais,iso,codigo_telefono) VALUES ('Libia','LY','218');
INSERT INTO Paises(nombre_pais,iso,codigo_telefono) VALUES ('Liechtenstein','LI','423');
INSERT INTO Paises(nombre_pais,iso,codigo_telefono) VALUES ('Lituania','LT','370');
INSERT INTO Paises(nombre_pais,iso,codigo_telefono) VALUES ('Luxemburgo','LU','352');
INSERT INTO Paises(nombre_pais,iso,codigo_telefono) VALUES ('Macao','MO','853');
INSERT INTO Paises(nombre_pais,iso,codigo_telefono) VALUES ('Macedônia','MK','389');
INSERT INTO Paises(nombre_pais,iso,codigo_telefono) VALUES ('Madagascar','MG','261');
INSERT INTO Paises(nombre_pais,iso,codigo_telefono) VALUES ('Malasia','MY','60');
INSERT INTO Paises(nombre_pais,iso,codigo_telefono) VALUES ('Malawi','MW','265');
INSERT INTO Paises(nombre_pais,iso,codigo_telefono) VALUES ('Mali','ML','223');
INSERT INTO Paises(nombre_pais,iso,codigo_telefono) VALUES ('Malta','MT','356');
INSERT INTO Paises(nombre_pais,iso,codigo_telefono) VALUES ('Marruecos','MA','212');
INSERT INTO Paises(nombre_pais,iso,codigo_telefono) VALUES ('Martinica','MQ',NULL);
INSERT INTO Paises(nombre_pais,iso,codigo_telefono) VALUES ('Mauricio','MU','230');
INSERT INTO Paises(nombre_pais,iso,codigo_telefono) VALUES ('Mauritania','MR','222');
INSERT INTO Paises(nombre_pais,iso,codigo_telefono) VALUES ('Mayotte','YT','262');
INSERT INTO Paises(nombre_pais,iso,codigo_telefono) VALUES ('México','MX','52');
INSERT INTO Paises(nombre_pais,iso,codigo_telefono) VALUES ('Micronesia','FM','691');
INSERT INTO Paises(nombre_pais,iso,codigo_telefono) VALUES ('Moldavia','MD','373');
INSERT INTO Paises(nombre_pais,iso,codigo_telefono) VALUES ('Mónaco','MC','377');
INSERT INTO Paises(nombre_pais,iso,codigo_telefono) VALUES ('Mongolia','MN','976');
INSERT INTO Paises(nombre_pais,iso,codigo_telefono) VALUES ('Montenegro','ME','382');
INSERT INTO Paises(nombre_pais,iso,codigo_telefono) VALUES ('Montserrat','MS','1 664');
INSERT INTO Paises(nombre_pais,iso,codigo_telefono) VALUES ('Mozambique','MZ','258');
INSERT INTO Paises(nombre_pais,iso,codigo_telefono) VALUES ('Namibia','NA','264');
INSERT INTO Paises(nombre_pais,iso,codigo_telefono) VALUES ('Nauru','NR','674');
INSERT INTO Paises(nombre_pais,iso,codigo_telefono) VALUES ('Nepal','NP','977');
INSERT INTO Paises(nombre_pais,iso,codigo_telefono) VALUES ('Nicaragua','NI','505');
INSERT INTO Paises(nombre_pais,iso,codigo_telefono) VALUES ('Niger','NE','227');
INSERT INTO Paises(nombre_pais,iso,codigo_telefono) VALUES ('Nigeria','NG','234');
INSERT INTO Paises(nombre_pais,iso,codigo_telefono) VALUES ('Niue','NU','683');
INSERT INTO Paises(nombre_pais,iso,codigo_telefono) VALUES ('Noruega','NO','47');
INSERT INTO Paises(nombre_pais,iso,codigo_telefono) VALUES ('Nueva Caledonia','NC','687');
INSERT INTO Paises(nombre_pais,iso,codigo_telefono) VALUES ('Nueva Zelanda','NZ','64');
INSERT INTO Paises(nombre_pais,iso,codigo_telefono) VALUES ('Omán','OM','968');
INSERT INTO Paises(nombre_pais,iso,codigo_telefono) VALUES ('Países Bajos','NL','31');
INSERT INTO Paises(nombre_pais,iso,codigo_telefono) VALUES ('Pakistán','PK','92');
INSERT INTO Paises(nombre_pais,iso,codigo_telefono) VALUES ('Palau','PW','680');
INSERT INTO Paises(nombre_pais,iso,codigo_telefono) VALUES ('Palestina','PS',NULL);
INSERT INTO Paises(nombre_pais,iso,codigo_telefono) VALUES ('Panamá','PA','507');
INSERT INTO Paises(nombre_pais,iso,codigo_telefono) VALUES ('Papúa Nueva Guinea','PG','675');
INSERT INTO Paises(nombre_pais,iso,codigo_telefono) VALUES ('Paraguay','PY','595');
INSERT INTO Paises(nombre_pais,iso,codigo_telefono) VALUES ('Perú','PE','51');
INSERT INTO Paises(nombre_pais,iso,codigo_telefono) VALUES ('Polinesia Francesa','PF','689');
INSERT INTO Paises(nombre_pais,iso,codigo_telefono) VALUES ('Polonia','PL','48');
INSERT INTO Paises(nombre_pais,iso,codigo_telefono) VALUES ('Portugal','PT','351');
INSERT INTO Paises(nombre_pais,iso,codigo_telefono) VALUES ('Puerto Rico','PR','1');
INSERT INTO Paises(nombre_pais,iso,codigo_telefono) VALUES ('Qatar','QA','974');
INSERT INTO Paises(nombre_pais,iso,codigo_telefono) VALUES ('Reino Unido','GB','44');
INSERT INTO Paises(nombre_pais,iso,codigo_telefono) VALUES ('República Centroafricana','CF','236');
INSERT INTO Paises(nombre_pais,iso,codigo_telefono) VALUES ('República Checa','CZ','420');
INSERT INTO Paises(nombre_pais,iso,codigo_telefono) VALUES ('República Dominicana','DO','1 809');
INSERT INTO Paises(nombre_pais,iso,codigo_telefono) VALUES ('Reunión','RE',NULL);
INSERT INTO Paises(nombre_pais,iso,codigo_telefono) VALUES ('Ruanda','RW','250');
INSERT INTO Paises(nombre_pais,iso,codigo_telefono) VALUES ('Rumanía','RO','40');
INSERT INTO Paises(nombre_pais,iso,codigo_telefono) VALUES ('Rusia','RU','7');
INSERT INTO Paises(nombre_pais,iso,codigo_telefono) VALUES ('Sahara Occidental','EH',NULL);
INSERT INTO Paises(nombre_pais,iso,codigo_telefono) VALUES ('Samoa','WS','685');
INSERT INTO Paises(nombre_pais,iso,codigo_telefono) VALUES ('Samoa Americana','AS','1 684');
INSERT INTO Paises(nombre_pais,iso,codigo_telefono) VALUES ('San Bartolomé','BL','590');
INSERT INTO Paises(nombre_pais,iso,codigo_telefono) VALUES ('San Cristóbal y Nieves','KN','1 869');
INSERT INTO Paises(nombre_pais,iso,codigo_telefono) VALUES ('San Marino','SM','378');
INSERT INTO Paises(nombre_pais,iso,codigo_telefono) VALUES ('San Martín (Francia)','MF','1 599');
INSERT INTO Paises(nombre_pais,iso,codigo_telefono) VALUES ('San Pedro y Miquelón','PM','508');
INSERT INTO Paises(nombre_pais,iso,codigo_telefono) VALUES ('San Vicente y las Granadinas','VC','1 784');
INSERT INTO Paises(nombre_pais,iso,codigo_telefono) VALUES ('Santa Elena','SH','290');
INSERT INTO Paises(nombre_pais,iso,codigo_telefono) VALUES ('Santa Lucía','LC','1 758');
INSERT INTO Paises(nombre_pais,iso,codigo_telefono) VALUES ('Santo Tomé y Príncipe','ST','239');
INSERT INTO Paises(nombre_pais,iso,codigo_telefono) VALUES ('Senegal','SN','221');
INSERT INTO Paises(nombre_pais,iso,codigo_telefono) VALUES ('Serbia','RS','381');
INSERT INTO Paises(nombre_pais,iso,codigo_telefono) VALUES ('Seychelles','SC','248');
INSERT INTO Paises(nombre_pais,iso,codigo_telefono) VALUES ('Sierra Leona','SL','232');
INSERT INTO Paises(nombre_pais,iso,codigo_telefono) VALUES ('Singapur','SG','65');
INSERT INTO Paises(nombre_pais,iso,codigo_telefono) VALUES ('Siria','SY','963');
INSERT INTO Paises(nombre_pais,iso,codigo_telefono) VALUES ('Somalia','SO','252');
INSERT INTO Paises(nombre_pais,iso,codigo_telefono) VALUES ('Sri lanka','LK','94');
INSERT INTO Paises(nombre_pais,iso,codigo_telefono) VALUES ('Sudáfrica','ZA','27');
INSERT INTO Paises(nombre_pais,iso,codigo_telefono) VALUES ('Sudán','SD','249');
INSERT INTO Paises(nombre_pais,iso,codigo_telefono) VALUES ('Suecia','SE','46');
INSERT INTO Paises(nombre_pais,iso,codigo_telefono) VALUES ('Suiza','CH','41');
INSERT INTO Paises(nombre_pais,iso,codigo_telefono) VALUES ('Surinám','SR','597');
INSERT INTO Paises(nombre_pais,iso,codigo_telefono) VALUES ('Svalbard y Jan Mayen','SJ',NULL);
INSERT INTO Paises(nombre_pais,iso,codigo_telefono) VALUES ('Swazilandia','SZ','268');
INSERT INTO Paises(nombre_pais,iso,codigo_telefono) VALUES ('Tadjikistán','TJ','992');
INSERT INTO Paises(nombre_pais,iso,codigo_telefono) VALUES ('Tailandia','TH','66');
INSERT INTO Paises(nombre_pais,iso,codigo_telefono) VALUES ('Taiwán','TW','886');
INSERT INTO Paises(nombre_pais,iso,codigo_telefono) VALUES ('Tanzania','TZ','255');
INSERT INTO Paises(nombre_pais,iso,codigo_telefono) VALUES ('Territorio Británico del Océano Índico','IO',NULL);
INSERT INTO Paises(nombre_pais,iso,codigo_telefono) VALUES ('Territorios Australes y Antárticas Franceses','TF',NULL);
INSERT INTO Paises(nombre_pais,iso,codigo_telefono) VALUES ('Timor Oriental','TL','670');
INSERT INTO Paises(nombre_pais,iso,codigo_telefono) VALUES ('Togo','TG','228');
INSERT INTO Paises(nombre_pais,iso,codigo_telefono) VALUES ('Tokelau','TK','690');
INSERT INTO Paises(nombre_pais,iso,codigo_telefono) VALUES ('Tonga','TO','676');
INSERT INTO Paises(nombre_pais,iso,codigo_telefono) VALUES ('Trinidad y Tobago','TT','1 868');
INSERT INTO Paises(nombre_pais,iso,codigo_telefono) VALUES ('Tunez','TN','216');
INSERT INTO Paises(nombre_pais,iso,codigo_telefono) VALUES ('Turkmenistán','TM','993');
INSERT INTO Paises(nombre_pais,iso,codigo_telefono) VALUES ('Turquía','TR','90');
INSERT INTO Paises(nombre_pais,iso,codigo_telefono) VALUES ('Tuvalu','TV','688');
INSERT INTO Paises(nombre_pais,iso,codigo_telefono) VALUES ('Ucrania','UA','380');
INSERT INTO Paises(nombre_pais,iso,codigo_telefono) VALUES ('Uganda','UG','256');
INSERT INTO Paises(nombre_pais,iso,codigo_telefono) VALUES ('Uruguay','UY','598');
INSERT INTO Paises(nombre_pais,iso,codigo_telefono) VALUES ('Uzbekistán','UZ','998');
INSERT INTO Paises(nombre_pais,iso,codigo_telefono) VALUES ('Vanuatu','VU','678');
INSERT INTO Paises(nombre_pais,iso,codigo_telefono) VALUES ('Venezuela','VE','58');
INSERT INTO Paises(nombre_pais,iso,codigo_telefono) VALUES ('Vietnam','VN','84');
INSERT INTO Paises(nombre_pais,iso,codigo_telefono) VALUES ('Wallis y Futuna','WF','681');
INSERT INTO Paises(nombre_pais,iso,codigo_telefono) VALUES ('Yemen','YE','967');
INSERT INTO Paises(nombre_pais,iso,codigo_telefono) VALUES ('Yibuti','DJ','253');
INSERT INTO Paises(nombre_pais,iso,codigo_telefono) VALUES ('Zambia','ZM','260');
INSERT INTO Paises(nombre_pais,iso,codigo_telefono) VALUES ('Zimbabue','ZW','263');
