//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Programa.Properties {
    using System;

    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Programa.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to wts.ItemName.
        /// </summary>
        public static string AppDisplayName {
            get {
                return ResourceManager.GetString("AppDisplayName", resourceCulture);
            }
        }
    
        /// <summary>
        ///   Looks up a localized string similar to ShellGoBackButton.
        /// </summary>
        public static string ShellGoBackButton {
            get {
                return ResourceManager.GetString("ShellGoBackButton", resourceCulture);
            }
        }
    
        /// <summary>
        ///   Looks up a localized string similar to ShellHamburgerButtonName.
        /// </summary>
        public static string ShellHamburgerButtonName {
            get {
                return ResourceManager.GetString("ShellHamburgerButtonName", resourceCulture);
            }
        }
    
        /// <summary>
        ///   Looks up a localized string similar to Personas.
        /// </summary>
        public static string PersonasPageTitle {
            get {
                return ResourceManager.GetString("PersonasPageTitle", resourceCulture);
            }
        }
    
        /// <summary>
        ///   Looks up a localized string similar to Personas.
        /// </summary>
        public static string ShellPersonasPage {
            get {
                return ResourceManager.GetString("ShellPersonasPage", resourceCulture);
            }
        }
    
        /// <summary>
        ///   Looks up a localized string similar to Telefonos.
        /// </summary>
        public static string TelefonosPageTitle {
            get {
                return ResourceManager.GetString("TelefonosPageTitle", resourceCulture);
            }
        }
    
        /// <summary>
        ///   Looks up a localized string similar to Telefonos.
        /// </summary>
        public static string ShellTelefonosPage {
            get {
                return ResourceManager.GetString("ShellTelefonosPage", resourceCulture);
            }
        }
    
        /// <summary>
        ///   Looks up a localized string similar to Actividades.
        /// </summary>
        public static string ActividadesPageTitle {
            get {
                return ResourceManager.GetString("ActividadesPageTitle", resourceCulture);
            }
        }
    
        /// <summary>
        ///   Looks up a localized string similar to Actividades.
        /// </summary>
        public static string ShellActividadesPage {
            get {
                return ResourceManager.GetString("ShellActividadesPage", resourceCulture);
            }
        }
    
        /// <summary>
        ///   Looks up a localized string similar to DataGrid.
        /// </summary>
        public static string DataGridPageTitle {
            get {
                return ResourceManager.GetString("DataGridPageTitle", resourceCulture);
            }
        }
    
        /// <summary>
        ///   Looks up a localized string similar to DataGrid.
        /// </summary>
        public static string ShellDataGridPage {
            get {
                return ResourceManager.GetString("ShellDataGridPage", resourceCulture);
            }
        }
    
        /// <summary>
        ///   Looks up a localized string similar to Agenda.
        /// </summary>
        public static string AgendaPageTitle {
            get {
                return ResourceManager.GetString("AgendaPageTitle", resourceCulture);
            }
        }
    
        /// <summary>
        ///   Looks up a localized string similar to Agenda.
        /// </summary>
        public static string ShellAgendaPage {
            get {
                return ResourceManager.GetString("ShellAgendaPage", resourceCulture);
            }
        }
    
        /// <summary>
        ///   Looks up a localized string similar to Monitoreo.
        /// </summary>
        public static string MonitoreoPageTitle {
            get {
                return ResourceManager.GetString("MonitoreoPageTitle", resourceCulture);
            }
        }
    
        /// <summary>
        ///   Looks up a localized string similar to Monitoreo.
        /// </summary>
        public static string ShellMonitoreoPage {
            get {
                return ResourceManager.GetString("ShellMonitoreoPage", resourceCulture);
            }
        }
    
        /// <summary>
        ///   Looks up a localized string similar to Informacion.
        /// </summary>
        public static string InformacionPageTitle {
            get {
                return ResourceManager.GetString("InformacionPageTitle", resourceCulture);
            }
        }
    
        /// <summary>
        ///   Looks up a localized string similar to Informacion.
        /// </summary>
        public static string ShellInformacionPage {
            get {
                return ResourceManager.GetString("ShellInformacionPage", resourceCulture);
            }
        }
    }
}
